In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel("시·군·구별_급여종류별_장기요양기관_현황_20200824144330.xlsx", thousands = ',')
df

,시·군·구별(1),시·군·구별(2),2018,2018.1,2018.2,2018.3,2018.4,2018.5,2018.6,2018.7,2018.8,2018.9,2018.10,2018.11,2018.12,2018.13
0,시·군·구별(1),시·군·구별(2),계,계,재가,재가,재가,재가,재가,재가,재가,재가,시설,시설,시설,시설
1,시·군·구별(1),시·군·구별(2),소계,소계,방문요양,방문목욕,방문간호,주야간보호,주야간보호,단기보호,단기보호,복지용구,노인요양시설,노인요양시설,노인요양공동생활가정,노인요양공동생활가정
2,시·군·구별(1),시·군·구별(2),기관수 (개),정원 (명),기관수 (개),기관수 (개),기관수 (개),기관수 (개),정원 (명),기관수 (개),정원 (명),기관수 (개),기관수 (개),정원 (명),기관수 (개),정원 (명)
3,서울,소계,3121,25878,1938,1672,129,392,10333,55,651,332,203,12174,312,2720
4,NaN,종로구,54,461,30,20,1,5,89,-,-,9,8,347,3,25
5,NaN,중구,28,260,18,17,1,5,143,1,11,2,3,97,1,9
6,NaN,용산구,53,385,37,32,3,7,162,-,-,6,4,214,1,9
7,NaN,성동구,64,691,44,35,4,11,264,1,9,3,3,391,3,27
8,NaN,광진구,113,1004,67,62,1,14,383,4,30,15,7,510,12,81
9,NaN,동대문구,145,1036,78,63,5,19,554,8,64,15,4,224,22,194
10,NaN,중랑구,186,1643,96,85,6,22,459,14,213,19,7,629,38,342
11,NaN,성북구,128,1028,86,82,5,14,338,-,-,11,15,657,4,33
12,NaN,강북구,144,1166,77,66,4,17,413,5,48,9,8,483,25,222
13,NaN,도봉구,177,1870,77,69,8,24,607,8,79,19,21,850,38,334
14,NaN,노원구,190,1821,124,109,11,24,726,3,26,10,11,884,21,185
15,NaN,은평구,158,1766,99,89,9,27,695,4,54,16,14,937,9,80
16,NaN,서대문구,96,859,56,45,3,17,364,1,6,7,11,433,7,56
17,NaN,마포구,82,697,61,52,2,14,367,-,-,9,3,312,2,18
18,NaN,양천구,174,1289,113,96,7,19,541,-,-,19,13,645,12,103
19,NaN,강서구,235,1789,163,127,8,21,677,-,-,38,17,991,14,121
20,NaN,구로구,148,1451,105,93,7,17,522,-,-,13,9,860,8,69
21,NaN,금천구,81,904,47,36,2,10,204,3,60,4,10,523,13,117
22,NaN,영등포구,135,571,90,80,5,12,310,-,-,19,1,118,17,143
23,NaN,동작구,100,584,68,61,4,14,331,-,-,11,3,190,7,63
24,NaN,관악구,148,1104,93,83,8,19,533,-,-,13,9,409,18,162
25,NaN,서초구,66,478,46,39,5,7,147,-,-,8,4,322,1,9
26,NaN,강남구,112,645,76,60,8,16,406,-,-,16,4,213,3,26
27,NaN,송파구,163,1276,104,92,8,20,568,3,51,18,7,526,15,131
28,NaN,강동구,141,1100,83,79,4,17,530,-,-,23,7,409,18,161

In [2]:
df=df.drop(df.index[0:4] , axis =0) ## 합계 행 삭제
df

,시·군·구별(1),시·군·구별(2),2018,2018.1,2018.2,2018.3,2018.4,2018.5,2018.6,2018.7,2018.8,2018.9,2018.10,2018.11,2018.12,2018.13
4,NaN,종로구,54,461,30,20,1,5,89,-,-,9,8,347,3,25
5,NaN,중구,28,260,18,17,1,5,143,1,11,2,3,97,1,9
6,NaN,용산구,53,385,37,32,3,7,162,-,-,6,4,214,1,9
7,NaN,성동구,64,691,44,35,4,11,264,1,9,3,3,391,3,27
8,NaN,광진구,113,1004,67,62,1,14,383,4,30,15,7,510,12,81
9,NaN,동대문구,145,1036,78,63,5,19,554,8,64,15,4,224,22,194
10,NaN,중랑구,186,1643,96,85,6,22,459,14,213,19,7,629,38,342
11,NaN,성북구,128,1028,86,82,5,14,338,-,-,11,15,657,4,33
12,NaN,강북구,144,1166,77,66,4,17,413,5,48,9,8,483,25,222
13,NaN,도봉구,177,1870,77,69,8,24,607,8,79,19,21,850,38,334
14,NaN,노원구,190,1821,124,109,11,24,726,3,26,10,11,884,21,185
15,NaN,은평구,158,1766,99,89,9,27,695,4,54,16,14,937,9,80
16,NaN,서대문구,96,859,56,45,3,17,364,1,6,7,11,433,7,56
17,NaN,마포구,82,697,61,52,2,14,367,-,-,9,3,312,2,18
18,NaN,양천구,174,1289,113,96,7,19,541,-,-,19,13,645,12,103
19,NaN,강서구,235,1789,163,127,8,21,677,-,-,38,17,991,14,121
20,NaN,구로구,148,1451,105,93,7,17,522,-,-,13,9,860,8,69
21,NaN,금천구,81,904,47,36,2,10,204,3,60,4,10,523,13,117
22,NaN,영등포구,135,571,90,80,5,12,310,-,-,19,1,118,17,143
23,NaN,동작구,100,584,68,61,4,14,331,-,-,11,3,190,7,63
24,NaN,관악구,148,1104,93,83,8,19,533,-,-,13,9,409,18,162
25,NaN,서초구,66,478,46,39,5,7,147,-,-,8,4,322,1,9
26,NaN,강남구,112,645,76,60,8,16,406,-,-,16,4,213,3,26
27,NaN,송파구,163,1276,104,92,8,20,568,3,51,18,7,526,15,131
28,NaN,강동구,141,1100,83,79,4,17,530,-,-,23,7,409,18,161

In [3]:
# 필요없는 데이터 삭제

df.drop(labels=["시·군·구별(1)","2018", "2018.2","2018.3","2018.4","2018.5","2018.6","2018.7","2018.8","2018.9","2018.10","2018.11","2018.12","2018.13"], axis=1, inplace=True)

In [4]:
df

   시·군·구별(2) 2018.1
4        종로구    461
5         중구    260
6        용산구    385
7        성동구    691
8        광진구   1004
9       동대문구   1036
10       중랑구   1643
11       성북구   1028
12       강북구   1166
13       도봉구   1870
14       노원구   1821
15       은평구   1766
16      서대문구    859
17       마포구    697
18       양천구   1289
19       강서구   1789
20       구로구   1451
21       금천구    904
22      영등포구    571
23       동작구    584
24       관악구   1104
25       서초구    478
26       강남구    645
27       송파구   1276
28       강동구   1100

In [5]:
# 열 이름 변경
df.rename(columns = {"시·군·구별(2)":"구", "2018.1":"행정동별요양기관정원"}, inplace=True)

In [6]:
df

       구 행정동별요양기관정원
4    종로구        461
5     중구        260
6    용산구        385
7    성동구        691
8    광진구       1004
9   동대문구       1036
10   중랑구       1643
11   성북구       1028
12   강북구       1166
13   도봉구       1870
14   노원구       1821
15   은평구       1766
16  서대문구        859
17   마포구        697
18   양천구       1289
19   강서구       1789
20   구로구       1451
21   금천구        904
22  영등포구        571
23   동작구        584
24   관악구       1104
25   서초구        478
26   강남구        645
27   송파구       1276
28   강동구       1100

In [7]:
df.to_excel("요양기관.xlsx")

In [8]:
low = df.sort_values(by = ['행정동별요양기관정원', '구'], ascending = True).head(10)
low

       구 행정동별요양기관정원
5     중구        260
6    용산구        385
4    종로구        461
25   서초구        478
22  영등포구        571
23   동작구        584
26   강남구        645
7    성동구        691
17   마포구        697
16  서대문구        859

In [9]:
high = df.sort_values(by = ['행정동별요양기관정원', '구'], ascending = False).head(10)
high

      구 행정동별요양기관정원
13  도봉구       1870
14  노원구       1821
19  강서구       1789
15  은평구       1766
10  중랑구       1643
20  구로구       1451
18  양천구       1289
27  송파구       1276
12  강북구       1166
24  관악구       1104